name: netvault
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - libexpat=2.7.4
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.11.14
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiosqlite==0.20.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - apscheduler==3.10.4
      - bcrypt==5.0.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - coverage==7.13.4
      - cryptography==44.0.3
      - ecdsa==0.19.1
      - fastapi==0.115.14
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.11
      - iniconfig==2.3.0
      - invoke==2.2.1
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - paramiko==4.0.0
      - pluggy==1.6.0
      - ply==3.11
      - pyasn1==0.6.0
      - pycparser==3.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - pygments==2.19.2
      - pynacl==1.6.2
      - pysmi-lextudio==1.4.3
      - pysnmp-lextudio==6.3.0
      - pysnmpcrypto==0.0.4
      - pytest==8.4.2
      - pytest-asyncio==0.24.0
      - pytest-cov==4.1.0
      - python-dotenv==1.0.1
      - python-jose==3.3.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rsa==4.9.1
      - six==1.17.0
      - starlette==0.46.2
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - tzlocal==5.3.1
      - urllib3==2.6.3
      - uvicorn==0.34.3
      - watchfiles==1.1.1
      - websockets==16.0
prefix: C:\Users\nesal\miniconda3\envs\netvault
